<?php
/**
 * Room Row Template (Used by JavaScript)
 *
 * This file serves as documentation for the room structure
 * The actual HTML is generated in JavaScript (hcc-room-repeater.js)
 * but follows this structure.
 *
 * @package    Hotel_Cleaning_Calculator_Pro
 * @subpackage Hotel_Cleaning_Calculator_Pro/public/partials
 * @since      2.0.0
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Get room types for reference
$calculator = new HCC_Calculator();
$room_types = $calculator->get_active_room_types();

// Get translated strings
$room_type_label = get_option( 'hcc_text_room_type', __( 'Room Type', 'hotel-cleaning-calculator-pro' ) );
$room_area_label = get_option( 'hcc_text_room_area', __( 'Area (m²)', 'hotel-cleaning-calculator-pro' ) );
$subtotal_label = get_option( 'hcc_text_room_subtotal', __( 'Subtotal', 'hotel-cleaning-calculator-pro' ) );
$remove_label = get_option( 'hcc_text_remove_room', __( 'Remove', 'hotel-cleaning-calculator-pro' ) );
$select_room_type = get_option( 'hcc_text_select_room_type', __( 'Select Room Type', 'hotel-cleaning-calculator-pro' ) );

/*
 * ROOM CARD STRUCTURE (Generated by JavaScript)
 * 
 * <div class="hcc-room-card">
 *     
 *     <!-- Room Number Badge -->
 *     <div class="hcc-room-number">Room 1</div>
 *     
 *     <!-- Remove Button -->
 *     <button type="button" class="hcc-remove-room">Remove</button>
 *     
 *     <!-- Room Fields -->
 *     <div class="hcc-room-fields">
 *         
 *         <!-- Room Type Select -->
 *         <div class="hcc-form-group">
 *             <label class="hcc-form-label required">Room Type</label>
 *             <select class="hcc-select hcc-room-type" required>
 *                 <option value="">Select Room Type</option>
 *                 <!-- Options populated from hccData.roomTypes -->
 *             </select>
 *         </div>
 *         
 *         <!-- Room Area Input -->
 *         <div class="hcc-form-group">
 *             <label class="hcc-form-label required">Area (m²)</label>
 *             <input type="number" 
 *                    class="hcc-input hcc-room-area" 
 *                    placeholder="25" 
 *                    min="1" 
 *                    step="0.01" 
 *                    required/>
 *         </div>
 *         
 *     </div>
 *     
 *     <!-- Room Subtotal -->
 *     <div class="hcc-room-subtotal">
 *         <span class="hcc-room-subtotal-label">Subtotal:</span>
 *         <span class="hcc-room-subtotal-value">-</span>
 *     </div>
 *     
 * </div>
 */

/**
 * Example of how to render a static room card (for reference)
 * This would be used if you want to pre-populate rooms server-side
 */
?>

<!-- Example Static Room Card (Not used by default) -->
<div class="hcc-room-card hcc-room-static-example" style="display: none;">
    
    <div class="hcc-room-number"><?php _e( 'Room 1', 'hotel-cleaning-calculator-pro' ); ?></div>
    
    <button type="button" class="hcc-remove-room">
        <?php echo esc_html( $remove_label ); ?>
    </button>
    
    <div class="hcc-room-fields">
        
        <!-- Room Type -->
        <div class="hcc-form-group">
            <label class="hcc-form-label required">
                <?php echo esc_html( $room_type_label ); ?>
            </label>
            <select class="hcc-select hcc-room-type" required>
                <option value=""><?php echo esc_html( $select_room_type ); ?></option>
                <?php foreach ( $room_types as $room_type ) : ?>
                    <option value="<?php echo esc_attr( $room_type['id'] ); ?>">
                        <?php 
                        echo esc_html( $room_type['name'] ) . ' (' . 
                             esc_html( $calculator->format_price( $room_type['price_per_m2'] ) ) . '/m²)';
                        ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        
        <!-- Room Area -->
        <div class="hcc-form-group">
            <label class="hcc-form-label required">
                <?php echo esc_html( $room_area_label ); ?>
            </label>
            <input 
                type="number" 
                class="hcc-input hcc-room-area" 
                placeholder="25" 
                min="1" 
                step="0.01" 
                required
            />
        </div>
        
    </div>
    
    <!-- Subtotal -->
    <div class="hcc-room-subtotal">
        <span class="hcc-room-subtotal-label">
            <?php echo esc_html( $subtotal_label ); ?>:
        </span>
        <span class="hcc-room-subtotal-value">-</span>
    </div>
    
</div>

<?php
/**
 * Data structure passed to JavaScript
 * 
 * hccData.roomTypes = [
 *     {
 *         id: 'bedroom',
 *         name: 'Bedroom',
 *         description: 'Standard bedroom cleaning',
 *         price_per_m2: 5.00,
 *         active: true,
 *         icon: 'bed'
 *     },
 *     // ... more room types
 * ]
 */
?>